// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcFamilyMeetings.Models;

namespace MvcFamilyMeetings.Migrations
{
    [DbContext(typeof(MvcFamilyMeetingsContext))]
    [Migration("20190529035644_FM980308A1")]
    partial class FM980308A1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcFamilyMeetings.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<string>("Date")
                        .IsRequired();

                    b.Property<string>("I_C1");

                    b.Property<string>("I_C2");

                    b.Property<int>("I_I1");

                    b.Property<int>("I_I2");

                    b.Property<long>("Loan_Amount");

                    b.Property<string>("Loan_Date");

                    b.Property<int>("Member_Id");

                    b.Property<long>("Payment");

                    b.Property<long>("Remaining");

                    b.HasKey("Id");

                    b.ToTable("Loan");
                });

            modelBuilder.Entity("MvcFamilyMeetings.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<string>("Login_Date")
                        .IsRequired();

                    b.Property<int>("Member_Id");

                    b.Property<string>("Member_Name");

                    b.Property<string>("Mt_C1");

                    b.Property<string>("Mt_C2");

                    b.Property<int>("Mt_I1");

                    b.Property<int>("Mt_I2");

                    b.HasKey("Id");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("MvcFamilyMeetings.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address_Home");

                    b.Property<string>("Address_Work");

                    b.Property<string>("Comment");

                    b.Property<string>("Date_Enter_Meetings");

                    b.Property<string>("Date_Exit_Meetings");

                    b.Property<string>("E_Mail");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<long>("Last_Loan");

                    b.Property<string>("Last_Loan_Date");

                    b.Property<long>("Last_Loan_Remainig");

                    b.Property<int>("Level");

                    b.Property<string>("LoginName")
                        .IsRequired();

                    b.Property<string>("Login_Password")
                        .IsRequired();

                    b.Property<string>("Login_Password_Hint");

                    b.Property<string>("M_C1");

                    b.Property<string>("M_C2");

                    b.Property<string>("M_C3");

                    b.Property<string>("M_C4");

                    b.Property<int>("M_I1");

                    b.Property<int>("M_I2");

                    b.Property<int>("M_I3");

                    b.Property<int>("M_I4");

                    b.Property<int>("Meeting_Turn");

                    b.Property<string>("Mobile_No")
                        .IsRequired();

                    b.Property<int>("Numbers");

                    b.Property<string>("Phone_Home");

                    b.Property<string>("Phone_Work");

                    b.Property<long>("Saving_Cash");

                    b.HasKey("Id");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("MvcFamilyMeetings.Models.Saving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .IsRequired();

                    b.Property<int>("Member_Id");

                    b.Property<long>("Payment");

                    b.Property<string>("S_C1");

                    b.Property<string>("S_C2");

                    b.Property<int>("S_I1");

                    b.Property<int>("S_I2");

                    b.HasKey("Id");

                    b.ToTable("Saving");
                });
#pragma warning restore 612, 618
        }
    }
}
